#!/usr/bin/env python3
"""Convert the lark-cli API registry (raw/registry.json) into OpenAPI 3.0 YAML.

One self-contained OpenAPI document is emitted per service into ``openapi/``.
Feishu/Lark-specific attributes that have no OpenAPI equivalent are preserved
as ``x-lark-*`` extensions:

+----------------------------+-----------------------------------------------+
| Registry field             | OpenAPI mapping                               |
+----------------------------+-----------------------------------------------+
| parameters (path/query)    | operation parameters                          |
| requestBody                | requestBody (application/json or multipart)   |
| responseBody               | responses.200 envelope ``data`` schema        |
| scopes / requiredScopes    | x-lark-scopes / x-lark-required-scopes        |
| accessTokens               | x-lark-access-tokens (user / tenant)          |
| risk                       | x-lark-risk (read / write / high-risk-write)  |
| danger                     | x-lark-danger                                 |
| tips                       | x-lark-tips                                   |
| docUrl                     | externalDocs.url                              |
| options [{value,desc}]     | enum + x-enum-descriptions                    |
+----------------------------+-----------------------------------------------+
"""
from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path

import yaml

from common import (MANIFEST_PATH, OPENAPI_DIR, RAW_REGISTRY_PATH, SERVERS,
                    clean_description, full_path, iter_methods,
                    load_local_registry, summary_of)

OPENAPI_VERSION = "3.0.3"
GENERATOR = "lark-openapi-spec tools/build_openapi.py"


# --------------------------------------------------------------------------
# YAML presentation
# --------------------------------------------------------------------------

class _Dumper(yaml.SafeDumper):
    """SafeDumper that renders multi-line strings as literal blocks and
    avoids aliases (each document is self-contained and diff-friendly)."""

    def ignore_aliases(self, data):  # noqa: D102
        return True


def _str_representer(dumper: yaml.Dumper, data: str):
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


_Dumper.add_representer(str, _str_representer)


def dump_yaml(doc: dict, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Generated by lark-openapi-spec — DO NOT EDIT BY HAND.\n"
        "# Source: lark-cli API registry "
        "(https://github.com/larksuite/cli, endpoint /api/tools/open/api_definition)\n"
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
        yaml.dump(doc, f, Dumper=_Dumper, allow_unicode=True,
                  sort_keys=False, width=120)


# --------------------------------------------------------------------------
# Field -> JSON Schema
# --------------------------------------------------------------------------

_NUMERIC = ("integer", "number")


def _coerce_number(value):
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return value
    try:
        f = float(str(value))
    except (TypeError, ValueError):
        return None
    return int(f) if f.is_integer() else f


def _coerce_literal(value, ftype: str):
    """Coerce a default/example/enum literal to the field's declared type.

    The registry stores many literals as strings even for integer/boolean
    fields ("500", "false"), which violates JSON Schema typing if copied
    verbatim. Unconvertible values are returned unchanged.
    """
    if not isinstance(value, str):
        return value
    if ftype == "integer":
        num = _coerce_number(value)
        return num if num is not None else value
    if ftype == "number":
        num = _coerce_number(value)
        return float(num) if num is not None else value
    if ftype == "boolean":
        low = value.strip().lower()
        if low in ("true", "false"):
            return low == "true"
    return value


def field_to_schema(field: dict) -> dict:
    """Recursively convert one registry Field into a JSON Schema fragment."""
    ftype = field.get("type") or "string"
    schema: dict = {}

    if ftype == "list":  # registry quirk: comma-separated query lists
        ftype = "array"
    if ftype == "file":
        schema["type"] = "string"
        schema["format"] = "binary"
    elif ftype == "array":
        schema["type"] = "array"
        props = field.get("properties")
        if props:
            item_schema, required = _object_schema(props)
            if required:
                item_schema["required"] = required
            schema["items"] = item_schema
        else:
            schema["items"] = {}
    elif ftype == "object":
        obj, required = _object_schema(field.get("properties") or {})
        schema.update(obj)
        if required:
            schema["required"] = required
    elif ftype in ("string", "integer", "number", "boolean"):
        schema["type"] = ftype
    else:  # unknown type: keep it visible instead of dropping
        schema["type"] = "string"
        schema["x-lark-original-type"] = ftype

    desc = clean_description(field.get("description"))
    if desc:
        schema["description"] = desc

    declared = schema.get("type", "string")
    if field.get("enum"):
        schema["enum"] = [_coerce_literal(v, declared) for v in field["enum"]]
    if field.get("options"):
        values, descs = [], {}
        for opt in field["options"]:
            values.append(_coerce_literal(opt.get("value"), declared))
            if opt.get("description"):
                descs[str(opt.get("value"))] = clean_description(opt["description"])
        schema["enum"] = values
        if descs:
            schema["x-enum-descriptions"] = descs

    if field.get("default") not in (None, ""):
        schema["default"] = _coerce_literal(field["default"], declared)
    if field.get("example") not in (None, ""):
        schema["example"] = _coerce_literal(field["example"], declared)

    for key, oapi_num, oapi_len in (("min", "minimum", "minLength"),
                                    ("max", "maximum", "maxLength")):
        raw = field.get(key)
        if raw in (None, ""):
            continue
        num = _coerce_number(raw)
        if num is None:
            continue
        if schema.get("type") in _NUMERIC:
            schema[oapi_num] = num
        elif schema.get("type") == "string":
            schema[oapi_len] = num
        elif schema.get("type") == "array":
            schema["minItems" if key == "min" else "maxItems"] = num

    return schema


def _object_schema(props: dict) -> tuple[dict, list]:
    """Build an object schema from registry properties; returns (schema, required)."""
    properties, required = {}, []
    for name, sub in props.items():
        properties[name] = field_to_schema(sub)
        if sub.get("required"):
            required.append(name)
    schema = {"type": "object", "properties": properties}
    return schema, required


# --------------------------------------------------------------------------
# Operation assembly
# --------------------------------------------------------------------------

def build_parameters(method: dict) -> list:
    params = []
    for name, field in sorted((method.get("parameters") or {}).items()):
        location = field.get("location") or "query"
        if location not in ("path", "query"):
            continue
        schema = field_to_schema(field)
        description = schema.pop("description", "")
        default = schema.pop("default", None)
        example = schema.pop("example", None)
        param = {
            "name": name,
            "in": location,
            "required": True if location == "path" else bool(field.get("required")),
            "schema": schema,
        }
        if description:
            param["description"] = description
        if default is not None:
            param["schema"]["default"] = default
        if example is not None:
            param["example"] = example
        if field.get("type") == "list":
            # comma-separated list in the query string
            param["style"] = "form"
            param["explode"] = False
            param["schema"] = {"type": "array", "items": {"type": "string"}}
        params.append(param)
    return params


def build_request_body(method: dict) -> dict | None:
    body = method.get("requestBody") or {}
    if not body:
        return None
    has_file = any(f.get("type") == "file" for f in body.values())
    content_type = "multipart/form-data" if has_file else "application/json"
    schema, required = _object_schema(body)
    if required:
        schema["required"] = required
    return {
        "required": bool(required),
        "content": {content_type: {"schema": schema}},
    }


def build_responses(method: dict) -> dict:
    resp_props = method.get("responseBody") or {}
    data_schema, data_required = _object_schema(resp_props)
    if data_required:
        data_schema["required"] = data_required
    envelope = {
        "type": "object",
        "description": "飞书开放平台统一响应信封；业务数据位于 data 字段。",
        "properties": {
            "code": {"type": "integer", "description": "错误码，0 表示成功"},
            "msg": {"type": "string", "description": "错误描述"},
            "data": data_schema,
        },
    }
    return {
        "200": {
            "description": "调用成功（业务错误通过 code 字段表达，见官方错误码文档）",
            "content": {"application/json": {"schema": envelope}},
        }
    }


def method_to_operation(svc: dict, resource: str, mname: str, method: dict) -> dict:
    desc = clean_description(method.get("description"))
    operation = {
        "operationId": f"{svc['name']}_{resource}_{mname}".replace(".", "_").replace("-", "_"),
        "summary": summary_of(desc),
        "tags": [resource],
    }
    if desc:
        operation["description"] = desc
    if method.get("docUrl"):
        operation["externalDocs"] = {
            "description": "飞书开放平台官方文档",
            "url": method["docUrl"],
        }

    params = build_parameters(method)
    if params:
        operation["parameters"] = params
    body = build_request_body(method)
    if body:
        operation["requestBody"] = body
    operation["responses"] = build_responses(method)

    # --- x-lark-* extensions: everything OpenAPI cannot express -------------
    if method.get("id"):
        operation["x-lark-method-id"] = method["id"]
    if method.get("scopes"):
        operation["x-lark-scopes"] = method["scopes"]
    if method.get("requiredScopes"):
        operation["x-lark-required-scopes"] = method["requiredScopes"]
    if method.get("accessTokens"):
        operation["x-lark-access-tokens"] = method["accessTokens"]
    if method.get("risk"):
        operation["x-lark-risk"] = method["risk"]
    if method.get("danger"):
        operation["x-lark-danger"] = True
    if method.get("tips"):
        operation["x-lark-tips"] = [clean_description(t) for t in method["tips"]]
    return operation


# --------------------------------------------------------------------------
# Service document
# --------------------------------------------------------------------------

def build_service_document(svc: dict, registry_version: str,
                           generated_at: str) -> dict:
    title = svc.get("title") or svc["name"]
    info_desc_parts = [clean_description(svc.get("description"))]
    info_desc_parts.append(
        "\n\n---\n\n本文档由 [lark-openapi-spec](https://github.com/larksuite/cli) "
        "项目从 lark-cli 的 API 注册表自动生成，非飞书官方文档。"
        "权威说明以 [飞书开放平台](https://open.feishu.cn/document) 为准。"
    )
    doc: dict = {
        "openapi": OPENAPI_VERSION,
        "info": {
            "title": f"飞书开放平台 · {title}",
            "description": "".join(info_desc_parts),
            "version": registry_version,
            "x-lark-service": svc["name"],
            "x-lark-service-api-version": svc.get("version"),
            "x-lark-registry-version": registry_version,
            "x-lark-generated-at": generated_at,
            "x-generator": GENERATOR,
        },
        "servers": SERVERS,
        "tags": [],
        "paths": {},
    }

    seen_tags: set[str] = set()
    for _svc, resource, mname, method in iter_methods({"services": [svc]}):
        path = full_path(svc, method)
        http_method = (method.get("httpMethod") or "GET").lower()
        operation = method_to_operation(svc, resource, mname, method)
        doc["paths"].setdefault(path, {})[http_method] = operation
        if resource not in seen_tags:
            seen_tags.add(resource)
            doc["tags"].append({"name": resource})
    return doc


# --------------------------------------------------------------------------
# Manifest
# --------------------------------------------------------------------------

def build_manifest(registry: dict, generated_at: str) -> dict:
    services = []
    total = 0
    for svc in registry.get("services") or []:
        count = sum(1 for _ in iter_methods({"services": [svc]}))
        total += count
        services.append({
            "name": svc["name"],
            "title": svc.get("title"),
            "api_version": svc.get("version"),
            "service_path": svc.get("servicePath"),
            "methods": count,
            "file": f"openapi/{svc['name']}.yaml",
        })
    return {
        "registry_version": registry.get("version"),
        "generated_at": generated_at,
        "generator": GENERATOR,
        "source": "https://open.feishu.cn/api/tools/open/api_definition?protocol=meta",
        "stats": {"services": len(services), "methods": total},
        "services": services,
    }


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", type=Path, default=RAW_REGISTRY_PATH,
                        help="path to the raw registry JSON snapshot")
    parser.add_argument("--out-dir", type=Path, default=OPENAPI_DIR)
    parser.add_argument("--manifest", type=Path, default=MANIFEST_PATH)
    args = parser.parse_args()

    registry = load_local_registry(args.registry)
    registry_version = registry.get("version") or "unknown"
    generated_at = datetime.datetime.now(datetime.timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ")

    count = 0
    for svc in registry.get("services") or []:
        doc = build_service_document(svc, registry_version, generated_at)
        out = args.out_dir / f"{svc['name']}.yaml"
        dump_yaml(doc, out)
        n_ops = sum(len(p) for p in doc["paths"].values())
        print(f"  {svc['name']:15s} -> {out.name:20s} ({n_ops} operations)")
        count += 1

    manifest = build_manifest(registry, generated_at)
    dump_yaml(manifest, args.manifest)
    print(f"\n{count} service documents written, "
          f"{manifest['stats']['methods']} operations total.")
    print(f"manifest -> {args.manifest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
