#!/usr/bin/env python3
"""Convert official API Explorer definitions (raw/explorer/) into OpenAPI 3.0.

One document per project is emitted into ``openapi/``. Differences from
the lark-cli track (tools/build_openapi.py):

- Explorer property lists are arrays of nodes (not maps) and include the
  complete response envelope (code/msg/data) — it is used as-is.
- Explorer-only extras are kept as extensions: errorMappings
  (x-lark-error-mappings), basicRateLimit (x-lark-rate-limit), pagination,
  idTransformInfos, file upload/download flags.
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import re
import sys
from pathlib import Path

import yaml

from dedupe_openapi import dedupe_document

GENERATOR = "lark-openapi-spec tools/build_openapi_full.py"

INDEX_PATH = Path("raw/explorer/index.json")
DEFS_DIR = Path("raw/explorer/defs")
OUT_DIR = Path("openapi")
MANIFEST_PATH = Path("manifest.yaml")

SERVERS = [
    {"url": "https://open.feishu.cn", "description": "飞书（中国大陆）"},
    {"url": "https://open.larksuite.com", "description": "Lark（国际版）"},
]

_TYPE_MAP = {
    "int": "integer",
    "float": "number",
    "boolean": "boolean",
    "string": "string",
    "object": "object",
}


# --------------------------------------------------------------------------
# YAML presentation (same style as the lark-cli track)
# --------------------------------------------------------------------------

class _Dumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


def _str_representer(dumper, data):
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


_Dumper.add_representer(str, _str_representer)


def dump_yaml(doc: dict, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Generated by lark-openapi-spec (full track) — DO NOT EDIT BY HAND.\n"
                "# Source: official API Explorer (open.feishu.cn/api-explorer, "
                "endpoint /api_explorer/v1)\n")
        yaml.dump(doc, f, Dumper=_Dumper, allow_unicode=True,
                  sort_keys=False, width=120)


# --------------------------------------------------------------------------
# Text / literal helpers
# --------------------------------------------------------------------------

_MD_EQ = re.compile(r"==(.+?)==")
_TTDOC = re.compile(r"\(/ssl:ttdoc(/[^)\s]+)\)")


def clean_text(text) -> str:
    if not text:
        return ""
    text = _MD_EQ.sub(r"`\1`", str(text))
    # /ssl:ttdoc/<path> is the doc-site's internal link scheme
    text = _TTDOC.sub(r"(https://open.feishu.cn/document\1)", text)
    return text.strip()


def coerce(value, ftype: str):
    if not isinstance(value, str):
        return value
    if ftype == "integer":
        try:
            return int(float(value))
        except ValueError:
            return value
    if ftype == "number":
        try:
            return float(value)
        except ValueError:
            return value
    if ftype == "boolean":
        low = value.strip().lower()
        if low in ("true", "false"):
            return low == "true"
    return value


# --------------------------------------------------------------------------
# Explorer node -> JSON Schema
# --------------------------------------------------------------------------

def node_to_schema(node: dict) -> dict:
    ntype = node.get("type") or "object"
    schema: dict = {}

    if ntype == "file":
        schema.update({"type": "string", "format": "binary"})
    elif ntype == "list":
        schema["type"] = "array"
        items = node.get("items")
        if isinstance(items, dict) and (items.get("properties") or items.get("type")):
            schema["items"] = node_to_schema(items)
        else:
            schema["items"] = {}
    elif ntype in _TYPE_MAP:
        schema["type"] = _TYPE_MAP[ntype]
        if ntype == "object":
            props, required = props_to_schema(node.get("properties") or [])
            if props:
                schema["properties"] = props
            if required:
                schema["required"] = required
    else:
        schema["type"] = "string"
        schema["x-lark-original-type"] = ntype

    desc = clean_text(node.get("description"))
    if desc:
        schema["description"] = desc

    if node.get("options"):
        values, descs, seen = [], {}, set()
        for opt in node["options"]:
            val = opt.get("value", opt.get("name"))
            val = coerce(val, schema.get("type", "string"))
            key = str(val)
            if key in seen:  # upstream quirk: duplicate enum options
                continue
            seen.add(key)
            values.append(val)
            if opt.get("description"):
                descs[key] = clean_text(opt["description"])
        schema["enum"] = values
        if descs:
            schema["x-enum-descriptions"] = descs

    if node.get("defaultValue") not in (None, ""):
        default = coerce(node["defaultValue"], schema.get("type", "string"))
        if schema.get("type") == "array" and not isinstance(default, list):
            # upstream quirk: scalar default on array fields ("100")
            try:
                parsed = json.loads(str(default))
                default = parsed if isinstance(parsed, list) else [parsed]
            except (ValueError, TypeError):
                default = None
        if default is not None and schema.get("enum") and default not in schema["enum"]:
            # upstream quirk: default is an enum *label*, not a value — drop it
            default = None
        if default is not None:
            schema["default"] = default
    if node.get("example") not in (None, ""):
        schema["example"] = node["example"]
    if node.get("format"):
        schema["format"] = node["format"]
    if node.get("idTypes"):
        schema["x-lark-id-types"] = node["idTypes"]
    return schema


def props_to_schema(props: list) -> tuple[dict, list]:
    properties, required = {}, []
    for child in props:
        name = child.get("name")
        if not name:
            continue
        properties[name] = node_to_schema(child)
        if child.get("required"):
            required.append(name)
    return properties, required


# --------------------------------------------------------------------------
# Operation assembly
# --------------------------------------------------------------------------

def colon_path(api_path: str) -> str:
    """:param -> {param} (Explorer uses colon-style path params)."""
    return re.sub(r":([A-Za-z_][\w]*)", r"{\1}", api_path or "")


def build_params(section_node: dict, location: str) -> list:
    params = []
    for child in (section_node or {}).get("properties") or []:
        name = child.get("name")
        if not name:
            continue
        schema = node_to_schema(child)
        description = schema.pop("description", "")
        example = schema.pop("example", None)
        param = {
            "name": name,
            "in": location,
            "required": True if location == "path" else bool(child.get("required")),
            "schema": schema,
        }
        if description:
            param["description"] = description
        if example is not None:
            param["example"] = example
        params.append(param)
    return params


def build_request_body(defn: dict) -> dict | None:
    request = defn.get("request") or {}
    body = request.get("body") or {}
    if not (body.get("properties") or body.get("items")):
        return None
    content_type = request.get("contentType") or "application/json"
    has_file = any((p.get("type") == "file") for p in body.get("properties") or [])
    if has_file:
        content_type = "multipart/form-data"
    schema = node_to_schema(body)
    required = schema.pop("required", None)
    return {"required": bool(required),
            "content": {content_type: {"schema": schema}}}


def build_responses(defn: dict) -> dict:
    body = (defn.get("response") or {}).get("body") or {}
    schema = node_to_schema(body) if (body.get("properties") or body.get("type")) \
        else {"type": "object", "properties": {}}
    return {"200": {
        "description": "调用成功（业务错误通过 code 字段表达；常见错误码见 x-lark-error-mappings）",
        "content": {"application/json": {"schema": schema}},
    }}


def method_to_operation(entry: dict, defn: dict, operation_id: str,
                        path_template: str = "") -> dict:
    op = {
        "operationId": operation_id,
        "summary": entry.get("title") or entry["apiName"],
        "tags": [entry["resource"]],
    }
    desc = clean_text(defn.get("description"))
    if desc and desc != op["summary"]:
        op["description"] = desc
    if entry.get("docPath"):
        op["externalDocs"] = {
            "description": "飞书开放平台官方文档",
            "url": "https://open.feishu.cn/document" + entry["docPath"],
        }

    params = build_params((defn.get("request") or {}).get("path"), "path")
    params += build_params((defn.get("request") or {}).get("query"), "query")
    # upstream quirk: some path template params are missing from the
    # definition's path section — add a string fallback so the doc resolves
    templated = set(re.findall(r"{([\w]+)}", path_template))
    declared = {p["name"] for p in params if p["in"] == "path"}
    for name in sorted(templated - declared):
        params.insert(0, {"name": name, "in": "path", "required": True,
                          "schema": {"type": "string"}})
    if params:
        op["parameters"] = params
    body = build_request_body(defn)
    if body:
        op["requestBody"] = body
    op["responses"] = build_responses(defn)

    # --- extensions ---------------------------------------------------------
    if defn.get("accessTokens"):
        op["x-lark-access-tokens"] = defn["accessTokens"]
    if defn.get("scopesOfDebugRequired"):
        op["x-lark-scopes"] = defn["scopesOfDebugRequired"]
    if defn.get("scopesOfFieldRequired"):
        op["x-lark-field-scopes"] = defn["scopesOfFieldRequired"]
    if defn.get("errorMappings"):
        op["x-lark-error-mappings"] = defn["errorMappings"]
    if defn.get("basicRateLimit"):
        op["x-lark-rate-limit"] = defn["basicRateLimit"]
    if defn.get("pagination"):
        op["x-lark-pagination"] = True
    if defn.get("idTransformInfos"):
        op["x-lark-id-transform"] = defn["idTransformInfos"]
    if defn.get("supportFileUpload"):
        op["x-lark-file-upload"] = True
    if defn.get("supportFileDownload"):
        op["x-lark-file-download"] = True
    return op


# --------------------------------------------------------------------------
# Project documents
# --------------------------------------------------------------------------

def def_filename(key: str) -> str:
    return key.replace("/", "__") + ".json"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--index", type=Path, default=INDEX_PATH)
    parser.add_argument("--defs-dir", type=Path, default=DEFS_DIR)
    parser.add_argument("--out-dir", type=Path, default=OUT_DIR)
    parser.add_argument("--manifest", type=Path, default=MANIFEST_PATH)
    args = parser.parse_args()

    with open(args.index, encoding="utf-8") as f:
        index = json.load(f)
    generated_at = datetime.datetime.now(datetime.timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ")

    projects: dict[str, list] = {}
    missing = []
    for key, entry in sorted(index.items()):
        def_path = args.defs_dir / def_filename(key)
        if not def_path.exists():
            missing.append(key)
            continue
        with open(def_path, encoding="utf-8") as f:
            defn = json.load(f)
        projects.setdefault(entry["project"], []).append((entry, defn))

    if missing:
        print(f"warning: {len(missing)} definitions missing from cache, "
              f"their APIs are skipped", file=sys.stderr)

    total_ops = 0
    for project, apis in sorted(projects.items()):
        doc = {
            "openapi": "3.0.3",
            "info": {
                "title": f"飞书开放平台 · {project} API（全量）",
                "description": (
                    f"飞书开放平台 `{project}` 项目的全部服务端接口。\n\n---\n\n"
                    "本文档由 [lark-openapi-spec](https://github.com/dayongxie/lark-openapi-spec) "
                    "项目从飞书官方 API Explorer 数据自动生成，非官方发布物。"
                    "权威说明以[飞书开放平台](https://open.feishu.cn/document)为准。"),
                # Filled after the document is built: a content-derived
                # version keeps unchanged files byte-identical across runs.
                "version": "",
                "x-lark-project": project,
                "x-lark-track": "full (official API Explorer)",
                "x-generator": GENERATOR,
            },
            "servers": SERVERS,
            "tags": [],
            "paths": {},
        }
        seen_tags: set[str] = set()
        used_op_ids: dict[str, str] = {}
        for entry, defn in apis:
            base_id = re.sub(r"\W+", "_",
                             f"{project}_{entry['resource']}_{entry['apiName']}")
            op_id = base_id
            if op_id in used_op_ids.values():
                op_id = f"{base_id}_{entry['version']}"
            if op_id in used_op_ids.values():
                op_id = f"{base_id}_{entry['version']}_{len(used_op_ids)}"
            used_op_ids[
                f"{entry['project']}/{entry['version']}/{entry['resource']}/{entry['apiName']}"] = op_id

            path = colon_path(entry.get("apiPath") or defn.get("apiPath") or "")
            if not path:
                continue
            method = (entry.get("httpMethod") or defn.get("httpMethod") or "GET").lower()
            op = method_to_operation(entry, defn, op_id, path)
            doc["paths"].setdefault(path, {})[method] = op
            if entry["resource"] not in seen_tags:
                seen_tags.add(entry["resource"])
                doc["tags"].append({"name": entry["resource"]})

        doc, n_comps = dedupe_document(doc)
        # Content-derived version: changes iff the document content changes,
        # so a rebuild over unchanged definitions is a git no-op.
        digest = hashlib.sha256(json.dumps(
            {k: doc[k] for k in ("paths", "components", "tags") if k in doc},
            ensure_ascii=False, sort_keys=True).encode("utf-8")).hexdigest()[:8]
        doc["info"]["version"] = f"1.0.0+{digest}"
        out = args.out_dir / f"{project}.yaml"
        dump_yaml(doc, out)
        n = sum(len(p) for p in doc["paths"].values())
        total_ops += n
        print(f"  {project:15s} -> {out.name:18s} ({n} operations, "
              f"{n_comps} shared components)")

    # merge full-track stats into the manifest
    manifest = {}
    if args.manifest.exists():
        with open(args.manifest, encoding="utf-8") as f:
            manifest = yaml.safe_load(f) or {}
    manifest["full_track"] = {
        "source": "https://open.feishu.cn/api_explorer/v1 (official API Explorer)",
        "generated_at": generated_at,
        "stats": {"projects": len(projects), "operations": total_ops},
        "directory": "openapi/",
    }
    dump_yaml(manifest, args.manifest)
    print(f"\n{len(projects)} project documents, {total_ops} operations total.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
